substitutions:
  name: apollo-air-sensor
  friendly_name: apollo-air-sensor
packages:
  ApolloAutomation.AIR-1: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: aUrcumo3RWK6T0mzf35lBK8cJtlXOFufh8751b/gEhI=

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  domain: .local.samir.systems
