substitutions:
  name: apollo-mtr1
  friendly_name: apollo-mtr1
packages:
  ApolloAutomation.MTR-1: github://ApolloAutomation/MTR-1/Integrations/ESPHome/MTR-1.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: aUrcumo3RWK6T0mzf35lBK8cJtlXOFufh8751b/gEhI=

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  domain: .local.samir.systems
