substitutions:
  name: plug-heater-04
  friendly_name: "Bedroom Heater Smart Plug 04"

packages:
  athom.smart-plug: github://sjafferali/esphome-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password