substitutions:
  device_name: plug-misc-12
  friendly_name: "Smart Plug Misc"

packages:
  athom.smart-plug-v2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name_add_mac_suffix: false


wifi:
  use_address: 192.168.50.22
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
time:
  - platform: homeassistant
    id: homeassistant_time
