substitutions:
  name: plug-brfan-03
  friendly_name: "Bedroom Fan Smart Plug 03"

packages:
  athom.smart-plug: github://sjafferali/esphome-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password