substitutions:
  name: plug-brdak-02
  friendly_name: "Bedroom Dakboard Smart Plug 02"

packages:
  athom.smart-plug: github://sjafferali/esphome-configs/athom-smart-plug.yaml
esphome:
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password